FROM node:16

RUN mkdir -p /app

WORKDIR /app

RUN yarn install

RUN yarn global add @quasar/cli

RUN yarn add express serve-static connect-history-api-fallback

COPY . .

RUN yarn build

CMD [ "yarn", "start" ]