language: generic

services:
 - docker

 stages:
  - build

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
  - sudo chmod +x /usr/bin/docker-compose

jobs:
  include:
    - stage: build
      script: docker-compose up
