version: '3.9'

services: 
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=myproject
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=password
    api:
        build: ./api
        command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
        depends_on: 
            - db
        env_file: 
            - .env
    client:
        build: ./client
        ports: 
            - "8080:8080"
        depends_on:
            - api
