name: CI API

on:
  push:
    branches: [ master ]
    paths:
      - "api/**"
  pull_request:
    branches: [ master ]
    paths:
      - "api/**"    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build api
        run: docker-compose up -d api
      - name: Run test
        run: docker-compose run api python manage.py test

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [ build, sonarcloud ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy docker container to heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: guilhermelml@gmail.com
          heroku_api_key: ${{ secrets.HEROKKU_API_KEY }}
          heroku_app_name: gces-ti-api
          dockerfile_directory: ./api/
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web