name: CI CLIENT

on:
  push:
    branches: [ master ]
    paths:
      - "client/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client
        run: docker-compose up -d client
      - name: Run tests
        run: docker-compose run client quasar test --unit jest
      - name: Publish tests to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./client/coverage/coverage-final.json
          flags: unittests
          fail_ci_if_error: true
          verbose: false

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: client
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [ build, sonarcloud ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy docker container to heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: guilhermelml@gmail.com
          heroku_api_key: ${{ secrets.HEROKKU_API_KEY }}
          heroku_app_name: gces-ti-front
          dockerfile_directory: ./client/
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web